### ISSUE TITLE
Track if posts have been fulfilled

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#464]
Use existing fulfilled_at database column. Make sure it can be set/unset. 
What else might we want/need to do for this?

**Comment by cpolitano** [comment]
@tibetsprague Did we decide that `fulfilled_at` does in fact need to be reversible?

**Comment by cpolitano** [comment]
Moving the email notifications piece to another ticket.

**Comment by tibetsprague** [comment]
@cpolitano I think so. if only to reverse mistakes. but also because you might think something is fulfilled and then its not
