### ISSUE TITLE
Handle Public Posts on the backend

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#466]
Add field to determine whether a post should be public to everyone or only visible to the communities it is shared to.

- public/private flag - add `public` column to posts table which takes a boolean
- We decided to wait on this and just do a boolean for now: Create a `Public` community that public posts are added to by creating a record in posts_communities join table connecting the post to the public community

**Comment by cpolitano** [comment]
So are you thinking, add a `public` column that takes a boolean?

**Comment by tibetsprague** [comment]
did we decide to do both the flag and the community for now and figure out what makes more sense as we build and test it?

**Comment by tibetsprague** [comment]
When a public post if Flagged we send a notification to a specific set of super admins for an extra layer of moderation

**Comment by cpolitano** [comment]
@tibetsprague yeah I'd like to do both a public flag and the community. The flag will make it easy to identify and style public posts without having to always check its communities too. And yeah flagging public posts for moderation is covered in [#485 ]
