### ISSUE TITLE
Ability to notify via slack may lead to significant increase in interaction

### ISSUE THREAD

**Issue by Connoropolous** [Hylozoic/hylo-node#50]
My perspective on hylo is that, unless you have the app installed, the 'pace of conversation' is slower than ideal. Getting it into a dimension of closer to realtime interactivity, almost chat, could really increase engagement. A great starting point for this, I think, would be 'push to slack' notifications of activity. I've built these kinds of things before, what this requires is
- [ ] to decide upon what models from hylo can be tracked in slack: a post, a community, a network, a project? 
- [ ] the addition of minimal UI to accept the depositing of a 'webhook' url, by a user
- [ ] documentation somewhere for users of what to do to retrieve a slack webhook url
- [ ] extension of the current notifications code to post to slack webhooks, when present on a resource

Once again, I may be interested to actually write and submit a PR for this, but I would want to get feedback here first.

**Comment by Connoropolous** [comment]
Slack is where the people are, and where their attention is.

**Comment by edwardwest** [comment]
Yes-- agreed-- to a certain extent having the mobile app installed helps
with this, as there are push notifications for every post-- but there is
more that could be done.

I would love it if you took a look at how to do this, Connor--

>
>    - to decide upon what models from hylo can be tracked in slack: a
>    post, a community, a network, a project?
>
>
I think for the first rollout, the best would be to track the "Community"
in a slack group-- this will catch all of the Projects as well, but not be
potentially overwhelming with Network activity


>
>    - the addition of minimal UI to accept the depositing of a 'webhook'
>    url, by a user
>    - documentation somewhere for users of what to do to retrieve a slack
>    webhook url
>    - extension of the current notifications code to post to slack
>    webhooks, when present on a resource
>
>
(I'll let Lawrence or Robbie weigh in on these three)

>
>
> Once again, I may be interested to actually write and submit a PR for
> this, but I would want to get feedback here first.
>
Thanks for taking a look at this!
Edward

**Comment by Connoropolous** [comment]
Progress underway!

<img width="766" alt="screen shot 2015-11-19 at 1 02 06 pm" src="https://cloud.githubusercontent.com/assets/1409121/11279331/dcfb9a2c-8ebd-11e5-8b9d-daf6a620a25d.png">

<img width="697" alt="screen shot 2015-11-19 at 1 02 18 pm" src="https://cloud.githubusercontent.com/assets/1409121/11279337/e84d1df6-8ebd-11e5-9d21-f4e2f0f031fb.png">

- [x] migration written
- [x] UI added
- [ ] slack notification service written

**Comment by levity** [comment]
Looking good so far!

**Comment by Connoropolous** [comment]
<img width="748" alt="screen shot 2015-11-19 at 5 23 12 pm" src="https://cloud.githubusercontent.com/assets/1409121/11287680/93d0fb2a-8eeb-11e5-811e-68faef00bab9.png">

**Comment by edwardwest** [comment]
this is awesome, Connor!

Thank you!
Edward

On Thursday, November 19, 2015, Connor Turland <notifications@github.com>
wrote:

> [image: screen shot 2015-11-19 at 5 23 12 pm]
> <https://cloud.githubusercontent.com/assets/1409121/11287680/93d0fb2a-8eeb-11e5-811e-68faef00bab9.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hylozoic/hylo-node/issues/50#issuecomment-158233394>.
>


-- 
_______________________
*Edward West*
mobile 415.225.7335
Facebook <http://www.facebook.com/edwardjwest>  Twitter
<http://www.twitter.com/edwardwest>  LinkedIn
<http://www.linkedin.com/in/edwardwest>
