### ISSUE TITLE
Send announcement notification emails

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#505]
We are getting complaints that posting an announcement is not sending out notification emails

**Comment by lorenjohnson** [comment]
This once kept ringing in my ears, and it took me a dive back through our notifications setup in `hylo-node` to remember why: We have never had an email template for "Announcements". They were implemented as a push and in-app notification only. We need to craft a template in SendWithUs and build this option into the notifications system.  Not a lot of work, but slightly above trivial.

**Comment by tibetsprague** [comment]
oh interesting, ok well i say we do it. do you need more input on that?
