### ISSUE TITLE
Fetching recent activity on member profile is broken

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#538]
It is joining posts table twice

**Comment by lorenjohnson** [comment]
Also -- graphql query which demonstrates the issue: 

https://www.hylo.com/noo/graphql?query=query%20RecentActivity(%24id%3A%20ID%2C%20%24order%3A%20String%2C%20%24sortBy%3A%20String%2C%20%24offset%3A%20Int%2C%20%24search%3A%20String%2C%20%24filter%3A%20String%2C%20%24first%3A%20Int%2C%20%24topic%3A%20ID%2C%20%24boundingBox%3A%20%5BPointInput%5D)%20%7B%20%20person(id%3A%20%24id)%20%7B%20%20%20%20id%20%20%20%20comments(first%3A%20%24first%2C%20order%3A%20%24order)%20%7B%20%20%20%20%20%20items%20%7B%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20text%20%20%20%20%20%20%20%20creator%20%7B%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20post%20%7B%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20title%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20attachments%20%7B%20%20%20%20%20%20%20%20%20%20type%20%20%20%20%20%20%20%20%20%20url%20%20%20%20%20%20%20%20%20%20position%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20createdAt%20%20%20%20%20%20%7D%20%20%20%20%7D%20%20%20%20posts(first%3A%20%24first%2C%20offset%3A%20%24offset%2C%20sortBy%3A%20%24sortBy%2C%20search%3A%20%24search%2C%20filter%3A%20%24filter%2C%20topic%3A%20%24topic%2C%20boundingBox%3A%20%24boundingBox%2C%20order%3A%20%22desc%22)%20%7B%20%20%20%20%20%20hasMore%20%20%20%20%20%20items%20%7B%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20announcement%20%20%20%20%20%20%20%20title%20%20%20%20%20%20%20%20details%20%20%20%20%20%20%20%20type%20%20%20%20%20%20%20%20creator%20%7B%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20name%20%20%20%20%20%20%20%20%20%20avatarUrl%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20createdAt%20%20%20%20%20%20%20%20updatedAt%20%20%20%20%20%20%20%20isPublic%20%20%20%20%20%20%20%20fulfilledAt%20%20%20%20%20%20%20%20startTime%20%20%20%20%20%20%20%20endTime%20%20%20%20%20%20%20%20myEventResponse%20%20%20%20%20%20%20%20commenters(first%3A%203)%20%7B%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20name%20%20%20%20%20%20%20%20%20%20avatarUrl%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20commentersTotal%20%20%20%20%20%20%20%20linkPreview%20%7B%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20title%20%20%20%20%20%20%20%20%20%20url%20%20%20%20%20%20%20%20%20%20imageUrl%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20location%20%20%20%20%20%20%20%20locationObject%20%7B%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20addressNumber%20%20%20%20%20%20%20%20%20%20addressStreet%20%20%20%20%20%20%20%20%20%20bbox%20%7B%20%20%20%20%20%20%20%20%20%20%20%20lat%20%20%20%20%20%20%20%20%20%20%20%20lng%20%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20%20center%20%7B%20%20%20%20%20%20%20%20%20%20%20%20lat%20%20%20%20%20%20%20%20%20%20%20%20lng%20%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20%20city%20%20%20%20%20%20%20%20%20%20country%20%20%20%20%20%20%20%20%20%20fullText%20%20%20%20%20%20%20%20%20%20locality%20%20%20%20%20%20%20%20%20%20neighborhood%20%20%20%20%20%20%20%20%20%20region%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20votesTotal%20%20%20%20%20%20%20%20myVote%20%20%20%20%20%20%20%20acceptContributions%20%20%20%20%20%20%20%20totalContributions%20%20%20%20%20%20%20%20communities%20%7B%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20name%20%20%20%20%20%20%20%20%20%20slug%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20attachments%20%7B%20%20%20%20%20%20%20%20%20%20type%20%20%20%20%20%20%20%20%20%20url%20%20%20%20%20%20%20%20%20%20position%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20postMemberships%20%7B%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20pinned%20%20%20%20%20%20%20%20%20%20community%20%7B%20%20%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20topics%20%7B%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20name%20%20%20%20%20%20%20%20%20%20postsTotal%20%20%20%20%20%20%20%20%20%20followersTotal%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20members%20%7B%20%20%20%20%20%20%20%20%20%20total%20%20%20%20%20%20%20%20%20%20hasMore%20%20%20%20%20%20%20%20%20%20items%20%7B%20%20%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20%20%20name%20%20%20%20%20%20%20%20%20%20%20%20avatarUrl%20%20%20%20%20%20%20%20%20%20%20%20bio%20%20%20%20%20%20%20%20%20%20%20%20tagline%20%20%20%20%20%20%20%20%20%20%20%20location%20%20%20%20%20%20%20%20%20%20%20%20skills(first%3A%20100)%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20items%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20eventInvitations%20%7B%20%20%20%20%20%20%20%20%20%20total%20%20%20%20%20%20%20%20%20%20hasMore%20%20%20%20%20%20%20%20%20%20items%20%7B%20%20%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20%20%20response%20%20%20%20%20%20%20%20%20%20%20%20person%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%20%20%20%20%20%20%20%20%20%20%20%20%20%20avatarUrl%20%20%20%20%20%20%20%20%20%20%20%20%20%20bio%20%20%20%20%20%20%20%20%20%20%20%20%20%20tagline%20%20%20%20%20%20%20%20%20%20%20%20%20%20location%20%20%20%20%20%20%20%20%20%20%20%20%20%20skills(first%3A%20100)%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20items%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%7D%20%20%20%20%7D%20%20%7D%7D&operationName=RecentActivity&variables=%7B%20%20%22first%22%3A%203%2C%22id%22%3A%20%2223247%22%2C%22order%22%3A%20%22desc%22%7D
