### ISSUE TITLE
Sendgrid - update to API keys by Jan 20

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#567]
We are emailing to inform you of the new deadline date of January 20th, 2021 to update your authentication method with Twilio SendGrid to API keys exclusively in order to ensure uninterrupted service and improve the security of your account. Our records show that one or more users with this email address used basic authentication with username and password for one or more of your SendGrid API requests or SMTP integration in the last 30 days. If you do not take action, those API requests will be rejected on January 20th, 2021.

https://sendgrid.com/docs/for-developers/sending-email/upgrade-your-authentication-method-to-api-keys/

**Comment by lorenjohnson** [comment]
@tibetsprague glad you got to this! As you likely discovered, SendGrid was rejecting sends from the 15th (e.g. https://app.sendwithus.com/#/logs/details/log_0865e91e4a26710b363a8ee2b64970e2-3, https://app.sendwithus.com/#/logs/details/log_5db665b1c36616855533b8edf90f6392-3, etc) but seems to have cleared-up on the 18th. Is that when you fixed it?

**Comment by tibetsprague** [comment]
Yes, it had to be fixed in SendwithUs, unfortunately SendWithUs was broken for 3 days or so and wouldn’t update the SendGrid connection. Then finally it worked!
