### ISSUE TITLE
Issue getting my database set up

### ISSUE THREAD

**Issue by Connoropolous** [Hylozoic/hylo-node#58]
@levity could you give me any help on this?

![screen shot 2015-11-18 at 4 56 53 pm](https://cloud.githubusercontent.com/assets/1409121/11255673/7fb45762-8e15-11e5-927a-3b067c4ee456.png)

**Comment by robbiecarlton** [comment]
Hey @Connoropolous 
Have you dumped the schema into your database?

cat migrations/schema.sql | psql [your_db_name]

**Comment by Connoropolous** [comment]
No, I haven't, thanks for the help :)

**Comment by Connoropolous** [comment]
That worked, thanks @robbiecarlton . I will close this issue, and submit a PR adding that to the README documentation.
