### ISSUE TITLE
Security vulnerability: Session weirdness

### ISSUE THREAD

**Issue by lorenjohnson** [Hylozoic/hylo-node#591]
I recently refreshed my local copy of production data for dev purposes (it's own issue), but when I loaded Web in dev I found I was auth'd as a user I have never auth'd as or even heard of. It was a strange experience and I have no idea exactly how it happened. I've seen similar things in the past, with at least a few users reporting having been inexplicably auth'd as another user. 

* Our current Session management involves a bag of hacks to make it work between web and mobile. We should probably be at least using a more standard JWT / token setup, but either way there are some weird things about our session management which probably should be pretty high up our list in any security audit.

**Comment by tibetsprague** [comment]
what hacks are we using for sessions? as far as i can tell we are using near standard Sails/Express/Connect session management with Redis. And after doing more research and thought im not convinced that JWTs are better. However if this is actually happening then there is definitely a problem, any ideas how to reproduce?
