### ISSUE TITLE
Unlicense?

### ISSUE THREAD

**Issue by pierreozoux** [Hylozoic/hylo-node#60]
Hi,

I'm not an expert about licenses, but I'm not sure it is the best.
http://programmers.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense

And this license is not present there neither: https://www.debian.org/legal/licenses/ :/

Thanks for clarifying :)

**Comment by levity** [comment]
Hi Pierre, thanks for bringing this to our attention! @edwardwest

**Comment by richchurcher** [comment]
Since the addition of AGPL, I guess this can be closed now! :)
