### ISSUE TITLE
SSL test - C grade

### ISSUE THREAD

**Issue by pierreozoux** [Hylozoic/hylo-node#62]
You could do better :)
https://www.ssllabs.com/ssltest/analyze.html?d=hylo.com

If you have doubts, I can help you.

I usually use https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by levity** [comment]
Thanks again! I've tweaked our configuration and we're now getting an A.

**Comment by pierreozoux** [comment]
Nice :)

You can even get an A+ :)
