### ISSUE TITLE
Mutations for a user to deactivate & delete themselves

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#620]
Deactivation:
- Back-end: set their active column to false. Log them out and delete their session. 
- If they try to log back in say this will re-activate your account, first asking them if they are sure they want to do that. 
- What should we show for posts and messages with deactivated users? Leave content for now we think... make sure people know it will be left up
- Show them in membership directory? No

Delete account:
- We don't delete the posts, we just delete the content of the post and change it to say Deleted Post, but leave comments on the post by other people. And change comments to say Deleted Comment. We will likely need a user that is called Deleted User that we point deleted posts and comments too as the creator/owner.
- What about upvotes? Could change to point to the Deleted User row in the users table, so we still keep the count the same...?
- Do we delete the groups they created? If other moderators we leave up as normal? If they were the only moderator in the group we pause/deactivate the group. Don't delete it but no more activity can happen in it. (This will also cause it to disappear for members of the group.) Do we need to send them a notification saying the group was deactivated?

**Comment by thomasgwatson** [comment]
"What about upvotes? Could change to point to the Deleted User row in the users table, so we still keep the count the same...?"

Normally I assume a user can't have more than one upvote on a post; so I'm assuming that we can only do this trick once before basically start removing the upvote count. Perhaps it is more sensible to just delete the upvote (or emoji react in the future)

Perhaps more importantly for future thinking, what do we do with a deleted users `votes` in important proposals? What are the implications of having a vote record where the numbers of votes change over time with deleted accounts? Interesting fodder for later discussions.

**Comment by thomasgwatson** [comment]
Users before deletion

![image](https://user-images.githubusercontent.com/5193218/145127700-8eefc8f2-7945-407c-bc38-d993c396599b.png)

Deleted one user, got this error:
![image](https://user-images.githubusercontent.com/5193218/145128248-6e7b54e3-27f8-44cb-ba01-02f29ca6f1d4.png)

**Comment by thomasgwatson** [comment]
After updating the `deletedUser` record with a `name` we get

![image](https://user-images.githubusercontent.com/5193218/145129273-89eac52c-57c1-4360-bffc-ccf9614b60fc.png)

**Comment by tibetsprague** [comment]
just realizes there's another thing we probably need to do: delete all the photos on AWS from the user's avatar and posts

**Comment by thomasgwatson** [comment]
Is there an existing lib/utility to delete uploads? Seeing a bunch of s3 stuff in the lib/uploader folder but looks like there are no delete utilities there

**Comment by thomasgwatson** [comment]
So, we need to delete data associated with:
`Banner url` from user table, 
`avatar url` from user table,
user_external_data records (I am somewhat guessing this is unused???), and
data associated with records in the media table that are related to comments and posts of the user

**Comment by thomasgwatson** [comment]
Also seeing a bunch of cloudfront urls... if we delete the underlying s3 object, will the CDN record get deleted as well? Or do I have to find a way to delete that too? I didn't find any references to cloudfront in the backend code

**Comment by thomasgwatson** [comment]
Seeing urls like: ` https://d3ngex8q79bk55.cloudfront.net/evo-uploads/user/26248/userAvatar/....` with the user id in the url :(

And a bunch of urls from gravatar and other external data sources... so seems like we'll have to just wipe the reference url in that case.

**Comment by thomasgwatson** [comment]
Based on last changes to the SQL, multiple deleted users in the same thread

![image](https://user-images.githubusercontent.com/5193218/145286979-7aa384a1-0c13-4be4-96d3-c7e95c66ed70.png)
