### ISSUE TITLE
Permanent URLs for specific comments within threads

### ISSUE THREAD

**Issue by gcassel** [Hylozoic/hylo-node#64]
Hylo currently has permanent URLs for posts, which can be accessed via each post's time stamp.   I'm wondering if there are plans (and any possible ETA) to add this functionality for specific comments within posts.  I've found that feature extremely useful in discussion spaces, both socially and administratively.   Thanks in advance for any feedback!

**Comment by levity** [comment]
I think that's a great idea. We don't have a spot on the roadmap for it yet, and at the moment my focus is on a major front-end refactoring, so it's unlikely that I'll work on the feature before that refactoring is more stable. But as always, pull requests are welcomed :)

**Comment by gcassel** [comment]
Thanks for sharing that!   I certainly understand the need to focus on a major front-end refactoring at this time.
