### ISSUE TITLE
Renew RapidSSL certificate

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#653]
Tibet renewed the cert, but doesnt know how to setup on digital ocean

Expires Aug 21

**Comment by lorenjohnson** [comment]
Renewed 🤘🏼

The basic steps to renew certificate as of this year, I think this was basically the same the last two renewals:

1) Pay for renewal of certificate
2) `ssh root@lb1.hylo.com` (password is in 1Password)
3) Generate a CSR `openssl req -new -newkey rsa:2048 -nodes -keyout server.key -out server.csr`. Alternatively, but discouraged, you can re-use the previous CSR--that is located at `/root/server.csr
4) Copy the contents of the `/root/server.csr`, return to the SSL Store renewal request and paste the contents of the CSR into the provided text box.
5) Follow the remaining steps as guided by the SSL Store to generate the renewed certificate.
6) Once completed successfully an email will arrive to `dev@hylo.com` (or wherever specified in the renewal process) with a link to the certificates. Once you follow the link select "A single .pem file containing all the certs" in the "File Type" dropdown and then click the Download button.
7) Open the downloaded `.pem` file and open it in a text editor. Return to the `lb1` and copy the contents of `/root/server.crt` and paste it at the top of the `.pem` file. Save the file.
8) `scp <whatevername>.pem root@lb1.hylo.com:new` 
9) Return to or open an SSH session to `l1b.hylo.com` and `cp /root/hylo.com.pem old` then `cp new/<whatevername>.pem /root/hylo.com.pem`. Run `service haproxy reload`.
10)  Navigate to `https://www.hylo.com` in the browser and confirm that the renewed certificate is being used (click on the lock next to the URL in the browser address bar to get the cert information).

**Comment by lorenjohnson** [comment]
Other things learned: 

As far as I can tell we're not using Heroku certificates at this time. 

All of the traffic to Hylo passes through our load balancer at `lb1.hylo.com` which proxies requests to `www.hylo.com/noo/*` and `www.hylo.com/socket.io/*` to the same paths on `node1.hylo.com` API. All requests to the two Heroku instances is currently done over HTTP, not HTTPS. 

This also means that traffic between this Digital Ocean VPS and our Heroku instances is happening as clear text vs remaining SSL encrypted. This is quiet problem but one which should at some point be addressed. Two options:

1) Retire the HAProxy load balancer / proxy server and have requests go directly to our Heroku instances. With some careful dismantling, and potential updates to how we handle session management, this should be entirely achievable. 

or

2) Rewrite the HAProxy rules such that they proxy to HTTPS URLs of our Heroku instances vs the HTTP. This would require that we maintain active certificates on both Evo and Node on Heroku. We've currently been already paying for certificates on both services so it should require not changes on the Heroku side.
