### ISSUE TITLE
SurveyStack Endpoint for Farm Groups

### ISSUE THREAD

**Issue by thomasgwatson** [Hylozoic/hylo-node#674]
POST endpoint (url not yet defined) that takes a to-be-determined json object that leads to the creation of several entities in the database. We will also need to come to some agreement about authorization.

At a minimum we expect it to create:
- a user
- a group
- a group extension (specifically the initial farm one)

Assuming that in the future when we offer a way to add farms via the Hylo interface, that we will create a separate GraphQL mutation to handle that.

**Comment by tibetsprague** [comment]
yes i think this is a duplicate of https://github.com/Hylozoic/hylo-node/issues/746
