### ISSUE TITLE
Add times + timezone to dates in email notifications

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#694]
Show when an event is happening in our email notifications

When displaying a date in an email notification add the timezone to the end, like we do for events on the web. 

Do the timestamps on the server store the zone coming from the front-end? Or are they all converted to a single server time zone in the database? If the former we can display the timezone of the event, if the latter let's pick UTC and show that for all events.

**Comment by thomasgwatson** [comment]
Looks like the columns all have +00 as their timezone, so are stored as UTC (Are we explicitly inserting them as UTC/epoch time?).

So looks like we'll have to add them as UTC time. The only alternative I can think of is to check/determine the timezone of the user receiving the email and send it in that, or instead provide a relative time (3 days and 6 hours away).

Perhaps a wider question is: should we store timezone information for events (are there other things that we should track timezone for??)

**Comment by thomasgwatson** [comment]
![image](https://user-images.githubusercontent.com/5193218/149420972-a4cede19-7945-4009-9648-da8561a2943f.png)

Basically all we'd need to do for now is add this to be clear that its UTC time. Still not a great user experience but we have a bit of work to do for it to do soemthing else

**Comment by tibetsprague** [comment]
Oh man I forgot we aren't event including event times in the email digests at all! that needs to happen. 

yeah unfortunately we dont explicitly store timezones with events or ask users for their timezone right now, so there's not much we can do. and yes looks like events in Announcements are in UTC, so lets definitely show that for now. but really we need to ask users for their timezone...
