### ISSUE TITLE
Add ability to save group location as a geoJSON shape

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#729]
New field in the database for the shape representing a group. TBD where to store this - right on the group table? or another location table row?
convert into PostGIS format in the DB

+ mutations needed to add/update these

how do we handle really large shape sizes? maybe dont allow them from the front end for now

**Comment by lorenjohnson** [comment]
Some potential issues around GeoJSON data:

- Total size of file/data
- Multiple points or regions in one file

Features/solutions discussed:

- Upload GeoJSON file option
- Text box entry (copy/pasted) of GeoJSON file

* Also, this is a group's "region" (or similar) vs location which it seems will remain a separate field and option.
