### ISSUE TITLE
issue running `npm run dev`

### ISSUE THREAD

**Issue by Connoropolous** [Hylozoic/hylo-node#77]
![screen shot 2016-02-09 at 11 29 29 am](https://cloud.githubusercontent.com/assets/1409121/12901422/80ba8fe0-cf20-11e5-8fc6-06d5d1a4f4ba.png)

I keep getting this, and can't trace the error easily :(

**Comment by Connoropolous** [comment]
@levity have you encountered this? any suggestions? :)

**Comment by robbiecarlton** [comment]
@Connoropolous don't know if this is related to your error, but hylo-node was recently upgraded to run on node 5.5.0, so if you haven't updated node and rebuilt everything in node_modules, you will probably get errors.

**Comment by Connoropolous** [comment]
yeah, it seems likely, but I did upgrade to node 5.5.0 and rebuild. however, I think I did also see one error come up along the way about xcodebuild. so maybe that's causing it

**Comment by Connoropolous** [comment]
I am still having this issue quite a bit, but not all of the time. it is very strange. but generally, it seemed to be further npm installing and rebuilding that started to make it work better.
