### ISSUE TITLE
Research membership subscription platforms to potentially use

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#802]

**Comment by thomasgwatson** [comment]
https://www.figma.com/file/ZM54VQ146kCjIVe5SfyafQ/Paid-Group-Membership?node-id=0%3A1

**Comment by tibetsprague** [comment]
Stripe could handle all the subscriptions stuff for us which would be nice, but pricier than building some pieces of it ourselves on top of basic stripe: https://stripe.com/billing https://stripe.com/billing/pricing

**Comment by thomasgwatson** [comment]
Ugh, Apple will want to take a cut. This will make iOS things annoying

**Comment by tibetsprague** [comment]
Yeah true. Wait, I thought if we dont have subscription stuff in the app at all then people can still use subscriptions they pay for online right? It could be confusing though because then people cant necessarily deal with groups on the app that are subscription based if they are not a member.

**Comment by thomasgwatson** [comment]
https://www.itechpost.com/articles/108706/20220114/apple-app-store-to-allow-external-payments-in-the-near-future.htm

Looks like Apple scooping fees from external payment sites is very much the subject of that big Epic VS Apple legal battle. A good chance it won't be a problem for us actually

**Comment by thomasgwatson** [comment]
Options:
- Stripe (https://stripe.com/docs/billing/subscriptions/build-subscriptions)
     Specifically their 'Connect' offering (https://stripe.com/docs/connect)
- Shopify (https://shopify.dev/apps/subscriptions#requirements)
- Maybe Chargify, but they are B2B focused (https://www.chargify.com/subscription-management/)
- Similarly Braintree (https://www.braintreepayments.com/features/recurring-billing)
- Or Chargebee (https://www.chargebee.com/recurring-payments-with-chargebee/)

But most of these seem focused on the more common use-case; a site that wants to offer users subscriptions. We are interested in allowing some of our users to offer subscriptions to *other* users. Seems like a bit of an annoying thing to search for, because the more obvious use-case takes up a lot of the search space

**Comment by thomasgwatson** [comment]
Considering this is dealing with money stuff (the need for a payment processor), a subscription layer on top of that, a UI for both mods and subscribers and all the changes we'll need to reflect subscription stuff through EVO and NODE... Hard to imagine we have many good options beyond Stripe 'Connect'.

**Comment by tibetsprague** [comment]
Agreed

**Comment by thomasgwatson** [comment]
Only semi-recent commentary on our use-case:

https://www.reddit.com/r/fintech/comments/o17n5z/are_there_any_alternatives_to_stripe_connect_or/

Braintree is limited to the USA only (boo)
Mollie is US only
Worldline is global and has partnered with ChargeBee for their subscription management: https://worldline.com/en/home/pressroom/press-releases/2021/pr-2021_10_19_01.html

Maybe the most interesting find from this thread is Adyen.
Adyen seems like a viable option; https://www.adyen.com/our-solution/marketplaces-and-platforms
Can't tell if its better than Stripe or not at this stage

**Comment by thomasgwatson** [comment]
https://rocketrides.io/ demo app for stripe connect 'express' experience. In one flow, it creates app account and stripe account for a service provider/merchant

**Comment by thomasgwatson** [comment]
Well, I digged around Adyen. They don't seem to have as obvious documentation about how to integrate platform users, where as it feels very obvious with Stripe. In some point in the future, Adyen might still be useful to integrate if they have access to countries we need that Stripe doesn't have. But that is very much a later problem.

So I am officially advising we go with Stripe

**Comment by tibetsprague** [comment]
Awesome, thanks, lets do it!
