### ISSUE TITLE
Custom Prize Challenge Application on SurveyStack OR Airtable/Typeform/Zapier

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#826]
We will work to develop a seamless application process for Salmon Nation prize challenge. We could use SurveyStack, a free and open-source survey tool that is already integrated with Hylo’s API. We can create a custom survey for the prize challenge application that then automatically creates a user account on Hylo. We will add the functionality for the application Project Post to be automatically created in the Salmon Nation network group on Hylo when the survey is submitted. This application will be linked on the Edge Prize landing page and will be the way that participants enter the Hylo group - they will receive an email after they complete the application inviting them into the network on Hylo. This would require allowing SurveyStack surveys to create posts not just groups. 

Alternatively we could look into Zapier integration with Hylo to allow another existing platform like TypeForm or Airtable forms to create a post in Hylo

**Comment by thomasgwatson** [comment]
SurveyStack backend is Node/Express

Checking with Greg about whether they'd be open to us making PRs
