### ISSUE TITLE
Validate parent group inclusion for Group Creation API

### ISSUE THREAD

**Issue by thomasgwatson** [Hylozoic/hylo-node#846]
Need to validate that 'parentIds' for group creation is actually associating the farm group with a parent group.
For example; this group was submitted, including 33804 as a parentId (OpenTEAM hylo group). But it was not added to OpenTEAM as a related group
https://www.codepile.net/pile/NBdgA8EX

**Comment by thomasgwatson** [comment]
Greg tried

openteam (restricted w/ questions, open) - _didn't work_
openteam (restricted w/out questions, open) - _didn't work_

Nat tried
Wolfe's Neck Center Hub, Protected / Open _worked_

**Comment by thomasgwatson** [comment]
3. openteam visibility: open, access: open _worked!_

**Comment by tibetsprague** [comment]
this is fixed by https://github.com/Hylozoic/hylo-node/issues/851
