### ISSUE TITLE
Reissue SSL cert for hylo.com

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#855]

**Comment by lorenjohnson** [comment]
Done. Certificate will expire again on August 23, 2023

**Comment by lorenjohnson** [comment]
STEPS to generate certificate: 

1) Re-issue certificate (or purchase new one) on SSLStore using signing request found at: `root@lb1.hylo.com:/server.csr`

2) Download `www_hylo_com.pem` and upload  to `root@lb1.hylo.com:/hylo.com.pem` (ideally backup old one first)

3) Login to `root@lb1.hylo.com:/server.csr` and run `service haproxy reload` and exit SSH session
