### ISSUE TITLE
Better UX for visiting resources I can't see

### ISSUE THREAD

**Issue by gdpelican** [Hylozoic/hylo-node#86]
I tried following a link to a hylo discussion I don't have access to (https://www.hylo.com/p/12131)

When logged out, it takes me to the login page, but when try to log in it fails and displays a flash message 'You don't have permission to view that.'
When logged in, it simply shows the loading screen with the same flash message

I'd expect that trying to visit an unauthorized resource would either take me to a 'you can't see this' landing page, or somewhere else in the app (my dashboard?) while displaying that flash message

:) <3

**Comment by edwardwest** [comment]
Thanks for this, James!

This is great feedback.

I'll put it on the list of improvements to make as we transition to React.

Much love,
Edward

**Comment by richchurcher** [comment]
Closing this as new version makes it mostly redundant :smile:
