### ISSUE TITLE
New groups have a default #general topic always added

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#874]
When a group is created add a #general GroupTag to it with is_default set to true. Also set visibility to pinned? Yes maybe, TBD.

**Comment by thomasgwatson** [comment]
Assuming that there isn't a `#general` Tag in the db already, and that I should do a little data migration to make that happen?

**Comment by thomasgwatson** [comment]
Do we want to add a `#general` tag/topic to all existing groups?
