### ISSUE TITLE
Make sure notifications are by default on when you join a new group

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#878]

**Comment by thomasgwatson** [comment]
- Created new prod user
- joined group
- posted in group on other account
- commented on post using other account, tagging new account
- received tag notification via email
- Looked up new user group_memberships in DB



![Image](https://user-images.githubusercontent.com/5193218/198699584-235f8276-567e-4fee-b8f2-2f1486f820f2.png)

**Comment by tibetsprague** [comment]
@brodeur @cpolitano can you see if you can show Tom a way to reproduce?

**Comment by tibetsprague** [comment]
closing until it comes back up
