### ISSUE TITLE
Improve notification link URLs for comment notifications

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#883]
- [ ] Clicking on a comment notification link (in app and in email) should open the post and scroll to that comment
- [x] Same with comment mention notifications
- [x] Comment should be highlighted to make it stand out

**Comment by thomasgwatson** [comment]
Maybe related @lorenjohnson comments? https://github.com/Hylozoic/hylo-node/issues/884#issuecomment-1302327599

**Comment by thomasgwatson** [comment]
Ok, so initial implementation thoughts

- Assuming this will be done by adding query params to the links. Something that uniquely ids the comment.
- So do we just expose the commentId in the query param? I guess we do that for posts, so we must be ok with exposing ids...

**Comment by lorenjohnson** [comment]
Why a querysearch vs `.../comments/:commentId`?

**Comment by thomasgwatson** [comment]
Ahh yes, I'm actually connecting your comments in #884 to this discussion and can do that instead :)
