### ISSUE TITLE
Table/model setup for roles/badges

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#920]
new table group_roles
- group_id - ID
- name - string
- emoji - string
- color - string?

new table member_roles
- group_id 
- user_id (index on pair of group_id & user_id)
- group_role_id

mutations to addGroupRole, removeGroupRole (also delete's all memberRoles? or just deactivates and hides?), addRoleToMember, removeRoleFromMember...

**Comment by thomasgwatson** [comment]
What do we think about the removal of a GroupRole and its impact on related MemberRoles?

I think we either have to delete both or inactivate both, but either way, be consistent across the little graph.

- if GroupRoles are to be deleted, then delete all the MemberRoles. Want that group role back? Create it again and re-add everyone to that role
- if GroupRoles are just deactived, then deactive all the attached MemberRoles. Want that group role back? Hit the button and it is reactivated, along with all the attached MemberRoles. Would have to add `active` columns in this instance

**Comment by tibetsprague** [comment]
I think deactivation is probably better here. People might want to “hide” a badge/role temporarily and this would get us that.

**Comment by thomasgwatson** [comment]
`export function makeMutations (expressContext, userId, isAdmin, fetchOne) {`

For makeMutations, if the `isAdmin` here scoped to the group in question, or a more generic sense of admin?

**Comment by tibetsprague** [comment]
No this means a super admin of all of Hylo

**Comment by thomasgwatson** [comment]
Ok, so following on the implications of deactivation in lieu of deletion:

So, essentially I was like "Well, might as well just make an UpdateGroupRole action", as it would work to change the `active` status of a GroupRole and also give us an option to allow editing the name, color, emoji, etc...

So do we even need the RemoveGroupRole?

Also for RemoveRoleFromMember; do we just want to delete here, not deactivat? There isn't really 'state', like the attributes of GroupRole that would be lost by deletion.

**Comment by tibetsprague** [comment]
I think update can handle deactivation. And sure RemoveRoleFromMember can just delete
