### ISSUE TITLE
Dev containers broken on macOS

### ISSUE THREAD

**Issue by birkskyum** [Hylozoic/hylo-node#925]
It crashes when I try to Reopen in Container.

<img width="1533" alt="Screenshot 2023-01-25 at 17 09 21" src="https://user-images.githubusercontent.com/74932975/214615056-9d7d196c-2495-4db3-880f-7315f13fd27f.png">

**Comment by tibetsprague** [comment]
Thanks for the report! No one on the current core team is using Docker so we have not stayed on top of this. Will try to get this working again in the next few weeks! I'm also curious to know what your interest is in getting Hylo setup.

**Comment by tibetsprague** [comment]
Gotcha, well i can help you get setup with the dev environment not using Docker if you want, the READMEs here and on hylo-evo (the front-end) should be pretty up to date. And we do hope to fix up the containers soon

**Comment by birkskyum** [comment]
> Gotcha, well i can help you get setup with the dev environment not using Docker if you want, the READMEs here and on hylo-evo (the front-end) should be pretty up to date. And we do hope to fix up the containers soon

Thanks - I'll proceed attempting that approach then and speak up if I get stuck there.

**Comment by birkskyum** [comment]
I'm not using hylo anymore, so I'll close. If it's of interest to the team to fix this, feel free to reopen.
