### ISSUE TITLE
Allow photos to be deleted from events, posts, projects

### ISSUE THREAD

**Issue by CarolynEco** [Hylozoic/hylo-node#987]
The 'x' to remove a photo that's been attached to a post, project or event does NOT remove the photo.  (Not in Chrome nor Firefox browsers).

**Comment by tibetsprague** [comment]
Fix for this coming very soon!

**Comment by CarolynEco** [comment]
Thanks!!

Carolyn Dare,
Tel: +44 7584 040135

https://www.ethosvo.org/building-a-sustainable-world/

**Comment by tibetsprague** [comment]
Fixed!
