### ISSUE TITLE
Track when posts and comments have been edited

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-node#994]
- [ ] Add an edited_at column to the posts table, and to the comments table, that are date times
- [ ] Add edited_at to the fields that can be added, updated and returned for those models

**Comment by KevinTriplett** [comment]
Can we use `updated_at`? Do we need to add another field?

`edited = updated_at != created_at`
    or
`edited = updated_at != null` (if updated_at is null until updated)

**Comment by KevinTriplett** [comment]
I'll develop against `updated_at` -- that way, the UI is ready to use whatever field we decide.

**Comment by tibetsprague** [comment]
No we definitely need a new field called edited_at. Was going to flesh out the description with more info about how to do that. But we might need a call. On Jul 1, 2024, at 6:24 PM, Kevin Triplett ***@***.***> wrote:﻿
I'll develop against updated_at -- that way, the UI is ready to use whatever field we decide.

**Comment by KevinTriplett** [comment]
Okay, got us scheduled for a call -- here's a quick screenshot of what I've got styled for the post header:

<img width="729" alt="Screenshot 2024-07-02 at 12 34 32 PM" src="https://github.com/Hylozoic/hylo-node/assets/5772/889d2428-f709-4820-a72c-8d0c5fecf302">
